### PR TITLE
Remove unnecessary `cat`

### PR DESCRIPTION
**Pull request by fuglede**

### CODE REVIEW

**Comment by fuglede** [comment]
The page appears to require an account. I doubt anything it that one-line commit is copyrightable, but just consider it public domain.

**Comment by fuglede** [comment]
In fact, the command does not appear to work; running `hstspreload batch` on a file containing only a single line will cause the application to do nothing forever.

**Comment by lgarron** [comment]
`hstspreload batch` only reads from stdin. I guess I could change it to `hstspreload batch < domains.txt`, but that's more shell-specific.

Also, unfortunately I cant accept contributions without a CLA signature. :-(
(Even if you consider it public domain, Google insists on a record that you assert you're giving us something you have the right to.)

**Comment by fuglede** [comment]
Certainly being forced to pipe in filenames goes against how command line tools typically work (on UNIX at least). Using `<` is better in that it avoids spawning a process, but I agree that it would be nicer to avoid. I [added a few lines](https://github.com/fuglede/hstspreload/commit/eca31819798a8ec285ea0e475bff0f29c73da6a0) to the PR for allowing filename arguments.

**Comment by lgarron** [comment]
> I added a few lines to the PR for allowing filename arguments.

Hmm, I intentionally only read from stdin because it's simpler – one behaviour, one code path. And some use cases will probably pipe directly.

Is there any benefit other than spawning one fewer process (which is pretty cheap compared to all the network activity of the scanning process)?

**Comment by fuglede** [comment]
Well, not from a performance perspective, but it's considered [bad form](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat) by enough people that I personally assumed that the application didn't require it. Then, when I ran it on a file with a few domains, I was wondering why it seemed to take forever. So, from my perspective, the main benefit is that it potentially saves someone some confusion.

**Comment by lgarron** [comment]
> So, from my perspective, the main benefit is that it potentially saves someone some confusion.

Oh, that's a pretty good point, actually. I think that outweighs the slight added complexity.

In that case, would you mind signing the CLA so I can accept the contribution?

**Comment by fuglede** [comment]
With the risk of sounding lazy, going through that seems like too much effort for such a small addition. Do feel free to copy it line by line or modify it if you think it's useful.

**Comment by lgarron** [comment]
> With the risk of sounding lazy, going through that seems like too much effort for such a small addition.

I kind of feel the same, but it's not too onerous (tightly scoped to your contributions), and pretty quick.

Copying your approach would be a bit sketchy for me (the amount of code doesn't make a difference), so I'd probably avoid it otherwise. :-(

**Comment by fuglede** [comment]
Okay, I read the entire thing a couple of times (well, four) and it looks reasonable enough although I find the definition of "submitted" so vague, that I do not have a huge clue about what it actually entails. Also, I guess "pretty quick" depends on your frame of reference; when you then go into thing, and you put in all of the details to create a user, you are prompted for verification of your phone number. I don't know what kind of trouble Google is trying to avoid, but that's certainly not anything I've seen in open source repositories before, and at that point I just gave up.

**Pull request closed without merging**
